//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSDec.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class AREntities : DbContext
    {
        public AREntities()
            : base("name=AREntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Daily_PassFail> Daily_PassFail { get; set; }
        public virtual DbSet<DailyActivity_Report> DailyActivity_Report { get; set; }
        public virtual DbSet<Daily_QSPdf> Daily_QSPdf { get; set; }
        public virtual DbSet<PortalPolicyPrints> PortalPolicyPrints { get; set; }
    
        public virtual int prc_DailyTapeImport()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_DailyTapeImport");
        }
    
        public virtual int prc_PolicyPrintFeedLoad()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("prc_PolicyPrintFeedLoad");
        }
    
        public virtual ObjectResult<prc_QSPDFsToPrint_Result> prc_QSPDFsToPrint()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<prc_QSPDFsToPrint_Result>("prc_QSPDFsToPrint");
        }
    }
}
