//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSDec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Daily_PassFail
    {
        public int Id { get; set; }
        public string PolicyNum { get; set; }
        public string Status { get; set; }
        public short TransID { get; set; }
        public System.DateTime PrintDate { get; set; }
    }
}
