//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace QSDec.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PortalPolicyPrints
    {
        public int Id { get; set; }
        public System.DateTime LoadDate { get; set; }
        public string PolicyNum { get; set; }
        public Nullable<short> MBrokerNo { get; set; }
        public short TransID { get; set; }
        public string FileName { get; set; }
        public string MInsuredName { get; set; }
        public string Trtype { get; set; }
        public Nullable<System.DateTime> effDate { get; set; }
        public string PolType { get; set; }
    }
}
